Models/Address.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Assignment.Models
{
    public class Address
    {
        [Key]
        public int AddressID { get; set; }
        public string? HouseNo { get; set; }
        public string? Street { get; set;}
        public string? City { get; set; }
        public string? District { get; set; }
        public int? ZipCode { get; set; }

        //Relationships
        public int PersonId { get; set; }
        [ForeignKey("PersonId")]
        public Person Person { get; set; }
    }
}

Models/Email.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Assignment.Models
{
    public class Email
    {
        [Key]
        public int EmailID { get; set; }
        [Display(Name = "Email")]
        public string? EmailAddress { get; set; }

        //Relationships

        public int PersonId { get; set; }
        [ForeignKey("PersonId")]
        public Person Person { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace Assignment.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Person.cs
using System.ComponentModel.DataAnnotations;

namespace Assignment.Models
{
    public class Person
    {
        [Key]
        public int PersonId { get; set; }

        [Display(Name = "Profile Picture")]
        [Required(ErrorMessage ="*Profile Picture is required")]
        public string? ProfilePicture { get; set; }
        [Display(Name ="First Name")]
        [Required(ErrorMessage = "*First Name is required")]
        public string? FirstName { get; set; }
        [Display(Name = "Last Name")]
        [Required(ErrorMessage = "*Last Name is required")]
        public string? LastName { get; set; }
        [Display(Name = "SSN")]
        public int? SSN { get; set; }
        [Display(Name = "Date of Birth")]
        public DateTime? DOB { get; set; }

        //Relationships

        public List<Email> Email { get; set; }
        public List<Address> Address { get; set; }
        public List<Phone> Phone { get; set; }


    }
}

Models/Phone.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Assignment.Models
{
    public class Phone
    {
        [Key]
        public int PhoneId { get; set; }
        [Display(Name = "Mobile")]
        public string? Mobile { get; set; }
        public string? FixedLine { get; set; }

        //Relationships
        public int PersonId { get; set; }
        [ForeignKey("PersonId")]
        public Person? Person { get; set; }
    }
}

Controllers/AddressesController.cs
using Assignment.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Assignment.Controllers
{
    public class AddressesController : Controller


    {
        //Inject AppDbcontext
        private readonly AppDbContext _context;

        public AddressesController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var alladdresses = await _context.Addresses.ToListAsync();
            return View(alladdresses);
        }
    }
}

Controllers/EmailsController.cs
using Assignment.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Assignment.Controllers
{
    public class EmailsController : Controller
    {
        private readonly AppDbContext _context;

        public EmailsController(AppDbContext context)
        {
            _context = context;
        }

        public  async Task<IActionResult> Index()
        {
            var allemails = await _context.Emails.ToListAsync();
            return View(allemails);
        }
    }
}

Controllers/HomeController.cs
using Assignment.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Assignment.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/PersonsController.cs
using Assignment.Data;
using Assignment.Data.Services;
using Assignment.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

//..../Persons/Index

namespace Assignment.Controllers
{
    public class PersonsController : Controller
    {
        private readonly IPersonsService _service;

        public PersonsController(IPersonsService service)
        {
            _service= service;
        }

        public async Task<IActionResult> Index()
        {
           
            var data = await _service.GetAllAsync();
            return View(data);
        }

        

        //Get : Persons/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Person person)
        {
            if(!ModelState.IsValid)
            {
                return View(person);
            }
            await _service.AddAsync(person);
            return RedirectToAction(nameof(Index));
        }

        //Get: Persons/Details/1

        public async Task<ActionResult> Details(int id)
        {
            var personDetails =await _service.GetByIdAsync(id);

            if (personDetails == null) return View("Not Found");
            return View(personDetails);
        }

        //Get : Persons/Update
        public async Task<IActionResult> Edit(int id)
        {
            var personDetails = await _service.GetByIdAsync(id);

            if (personDetails == null) return View("Not Found");
            
            return View(personDetails);
        }

        [HttpPut]
        public async Task<IActionResult> Edit(int id, Person person)
        {
            if (!ModelState.IsValid)
            {
                return View(person);
            }
            await _service.UpdateAsync(id,person);
            return RedirectToAction(nameof(Index));
        }

        //Get : Persons/Delete
        public async Task<IActionResult> Delete(int id)
        {
            var personDetails = await _service.GetByIdAsync(id);

            if (personDetails == null) return View("Not Found");

            return View(personDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var personDetails = await _service.GetByIdAsync(id);

            if (personDetails == null) return View("Not Found");

            await _service.DeleteAsync(id);
            
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Search(string searchString)
        {
            var data = await _service.GetAllAsync();

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(p => p.FirstName.StartsWith(searchString));
            }

            return View("Index", data);
        }

    }
}

Controllers/PhonesController.cs
using Assignment.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Assignment.Controllers
{
    public class PhonesController : Controller
    {
        private readonly AppDbContext _context;

        public PhonesController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var allphones = await _context.Phones.ToListAsync();
            return View(allphones);
        }
    }
}

Views/Addresses/Index.cshtml
@model IEnumerable<Address>



@{
    ViewData["Title"] = "List of Addresses";

}

<h5><b> Showing : Address Details of Persons</b></h5>
<div class="row">
    <div class="col">

        <table class="table table-striped table-hover table-bordered">
            <thead>
                <tr class="text-center">
                    <th> House No </th>
                    <th> Street </th>
                    <th> City </th>
                    <th> District </th>
                    <th> Zip Code </th>
                    <th> Person ID </th>


                    <th> Actions </th>

                </tr>
            </thead>


            <tbody>

                @foreach (var item in Model)
                {
                    <tr>
                        
                        <td class="align-middle"> @Html.DisplayFor(modelItem => item.HouseNo) </td>
                        <td class="align-middle"> @Html.DisplayFor(modelItem => item.Street)</td>
                        <td class="align-middle">@Html.DisplayFor(modelItem => item.City)</td>
                        <td class="align-middle">@Html.DisplayFor(modelItem => item.District)</td>
                        <td class="align-middle">@Html.DisplayFor(modelItem => item.ZipCode)</td>
                        <td class="align-middle">@Html.DisplayFor(modelItem => item.PersonId)</td>




                        <td class="align-middle">
                            <a class="btn btn-outline-primary"><i class="bi bi-pencil-square"></i> Edit</a> |
                            
                            <a class="btn btn-outline-danger"><i class="bi bi-trash"></i> Delete</a>
                        </td>
                    </tr>
                }


            </tbody>
        </table>

    </div>

</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h5>Software Engineer Position - Addovation</h5>
    <p>Practical Assignment by Kethaki Dissanayake</p>
</div>

Views/Persons/Create.cshtml
@model Person

@{
    ViewData["Title"] = "Add New Person";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Add a New Person</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-group text-center">
                        <img id="ProfilePicturePreview" style="max-width:200px" />
                    </div>
                    <div class="form-group">
                        <label asp-for="ProfilePicture" class="control-label"></label>
                        <input asp-for="ProfilePicture" class="form-control" />
                        <span asp-validation-for="ProfilePicture" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="FirstName" class="control-label"></label>
                        <input asp-for="FirstName" class="form-control" />
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="LastName" class="control-label"></label>
                        <input asp-for="LastName" class="form-control" />
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="SSN" class="control-label"></label>
                        <input asp-for="SSN" class="form-control" />
                        <span asp-validation-for="SSN" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="DOB" class="control-label"></label>
                        <input asp-for="DOB" class="form-control" />
                        <span asp-validation-for="DOB" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-outline-success float-end" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
                </form>
            </div>
        </div>

    </div>

</div>
@section Scripts{
    <script>
        $(document).ready(function (){
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $('#ProfilePicture').val();
        })

        $("#ProfilePicture").on("change", function(){
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $(this).val();
        })
    </script>
}

Views/Persons/Delete.cshtml
@model Person

@{
    ViewData["Title"] = "Delete Person";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Delete Confirmation @Model.FirstName</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">

                <div class="form-group text-center">
                    <img id="ProfilePicturePreview" style="max-width:200px" />
                </div>

                <div class="form-group">
                    <label asp-for="ProfilePicture" class="control-label"></label>
                    <input asp-for="ProfilePicture" class="form-control" readonly />
                    <span asp-validation-for="ProfilePicture" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="FirstName" class="control-label"></label>
                    <input asp-for="FirstName" class="form-control" readonly />
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="LastName" class="control-label"></label>
                    <input asp-for="LastName" class="form-control" readonly />
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SSN" class="control-label"></label>
                    <input asp-for="SSN" class="form-control" readonly />
                    <span asp-validation-for="SSN" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DOB" class="control-label"></label>
                    <input asp-for="DOB" class="form-control" readonly />
                    <span asp-validation-for="DOB" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <form asp-action="Delete" >
                      <input type="hidden" asp-for="PersonId"/>
                      <input type="submit" value="Confirm" class="btn btn-danger float-end"/>
                    </form>

                    <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                </div>

            </div>
        </div>

    </div>

</div>

@section Scripts{
    <script>
        $(document).ready(function () {
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $('#ProfilePicture').val();
        })




    </script>
}

Views/Persons/Details.cshtml
@model Person

@{
    ViewData["Title"] = "Add New Person";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Details for @Model.FirstName</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
               
                   <div class="form-group text-center">
                       <img id="ProfilePicturePreview" style="max-width:200px"/>
                   </div>
                   
                    <div class="form-group">
                        <label asp-for="ProfilePicture" class="control-label"></label>
                        <input asp-for="ProfilePicture" class="form-control" readonly />
                        <span asp-validation-for="ProfilePicture" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="FirstName" class="control-label"></label>
                        <input asp-for="FirstName" class="form-control" readonly />
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="LastName" class="control-label"></label>
                        <input asp-for="LastName" class="form-control" readonly />
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="SSN" class="control-label"></label>
                        <input asp-for="SSN" class="form-control" readonly />
                        <span asp-validation-for="SSN" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="DOB" class="control-label"></label>
                        <input asp-for="DOB" class="form-control" readonly/>
                        <span asp-validation-for="DOB" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <a class="btn btn-outline-success float-end" asp-action="Edit" asp-route-id="@Model.PersonId">Edit</a>
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
               
            </div>
        </div>

    </div>

</div>

@section Scripts{
    <script>
        $(document).ready(function (){
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $('#ProfilePicture').val();
        })       

    </script>
}

Views/Persons/Edit.cshtml
@model Person

@{
    ViewData["Title"] = "Update Person";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Update Person</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-group text-center">
                        <img id="ProfilePicturePreview" style="max-width:200px" />
                    </div>
                    <div class="form-group">
                        <label asp-for="ProfilePicture" class="control-label"></label>
                        <input asp-for="ProfilePicture" class="form-control" />
                        <span asp-validation-for="ProfilePicture" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="FirstName" class="control-label"></label>
                        <input asp-for="FirstName" class="form-control" />
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="LastName" class="control-label"></label>
                        <input asp-for="LastName" class="form-control" />
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="SSN" class="control-label"></label>
                        <input asp-for="SSN" class="form-control" />
                        <span asp-validation-for="SSN" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="DOB" class="control-label"></label>
                        <input asp-for="DOB" class="form-control" />
                        <span asp-validation-for="DOB" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Update" class="btn btn-outline-success float-end" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
                </form>
            </div>
        </div>

    </div>

</div>
@section Scripts{
    <script>
        $(document).ready(function () {
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $('#ProfilePicture').val();
        })

        $("#ProfilePicture").on("change", function () {
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $(this).val();
        })
    </script>
}

Views/Persons/Index.cshtml
@model IEnumerable<Person>



@{
    ViewData["Title"] = "List of Persons";

}

<div class="row">
  <div class="col md-8">
        <h5><b> Showing : Person Details</b></h5>
        <div class="text-white">
            <a asp-controller="Persons" asp-action="Create" class="btn btn-info"><i class="bi bi-plus-circle"></i>Add</a>

        </div>
  </div>
  <div class="col-md-4">
        <form class="form-inline my-2 my-lg-0" asp-controller="Persons" asp-action="Search" style="padding-right:0px">
            <input name="searchString" type="text" class="form-control" placeholder="Search for Person...">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
      </form>
  </div>

</div>


<div class="row">
    <div class="col">

        <table class="table table-striped table-hover table-bordered">
            <thead>
                <tr class="text-center">
                    <th> @Html.DisplayNameFor(model => model.ProfilePicture) </th>
                    <th> @Html.DisplayNameFor(model => model.FirstName) </th>
                    <th> @Html.DisplayNameFor(model => model.LastName) </th>
                    <th> @Html.DisplayNameFor(model => model.SSN) </th>
                   
                    <th> Actions </th>

                </tr>
            </thead>


            <tbody>
                
                @foreach(var item in Model)
                {
                <tr class="align-content-center">
                <td class="align-middle">
                    <img class="rounded-1" src="@item.ProfilePicture" alt="@item.FirstName" style="max-width:80px"/>
                </td>
                <td class="align-middle"> @Html.DisplayFor(modelItem => item.FirstName) </td>
                <td class="align-middle"> @Html.DisplayFor(modelItem => item.LastName)</td>
                <td class="align-middle">@Html.DisplayFor(modelItem => item.SSN)</td>
                        

                        
                        
                <td class="align-middle">
                    <a class="btn btn-outline-primary" asp-action="Edit" asp-route-id="@item.PersonId"><i class="bi bi-pencil-square"></i> Edit</a> |
                    <a class="btn btn-outline-info" asp-controller="Persons" asp-action="Details" asp-route-id="@item.PersonId"><i class="bi bi-eye"></i> Details</a> |
                            <a class="btn btn-outline-danger" asp-action="Delete" asp-route-id="@item.PersonId"><i class="bi bi-trash"></i> Delete</a>
                </td>
                </tr>
                }

                
            </tbody>
        </table>

    </div>

</div>

Views/Phones/Index.cshtml
@model IEnumerable<Phone>



@{
    ViewData["Title"] = "List of Phones";

}

<h5><b> Showing : Contact Details of Persons</b></h5>
<div class="row">
    <div class="col">

        <table class="table table-striped table-hover table-bordered">
            <thead>
                <tr class="text-center">
                    <th> Mobile </th>
                    <th> Fixed Line </th>
                    <th> Person ID </th>
                    

                    <th> Actions </th>

                </tr>
            </thead>


            <tbody>

                @foreach (var item in Model)
                {
                    <tr>
                        
                        <td class="align-middle"> @Html.DisplayFor(modelItem => item.Mobile) </td>
                        <td class="align-middle"> @Html.DisplayFor(modelItem => item.FixedLine)</td>
                        <td class="align-middle">@Html.DisplayFor(modelItem => item.PersonId)</td>




                        <td class="align-middle">
                            <a class="btn btn-outline-primary"><i class="bi bi-pencil-square"></i> Edit</a> |
                           
                            <a class="btn btn-outline-danger"><i class="bi bi-trash"></i> Delete</a>
                        </td>
                    </tr>
                }


            </tbody>
        </table>

    </div>

</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Assignment</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Assignment.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Persons" asp-action="Index">Person</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Addresses" asp-action="Index">Locations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Phones" asp-action="Index">Contacts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Emails" asp-action="Index">Emails</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Assignment - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>